config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'
  resources :autocomplete, only: [:index]
  resources :users, only: [:index, :destroy, :update, :edit]

  resources :movies do
    resources :reviews, only: [:create, :update, :destroy]
  end

  resources :searches, only: [:index]

  get '/show_movie', to: 'searches#show_movie', as: :show_movie

  resources :autocomplete, only: [:index]
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  validates :title, presence: true
  validates :year,
    presence: true,
    numericality: true
  validates :user,
    presence: true
end

app/models/movie_helper.rb
class MovieHelper
  def initialize(movies)
    @movies = movies
  end

  def find_movies(limit=5)
    trends = Hash.new({})

    @movies.each do |movie|
      trends[movie.id] = movie.reviews.count
    end

    trends = trends.sort_by { |reviews| reviews.count}
    trends = trends[0..limit-1]

    trends = trends.map do |arr|
      Movie.find(arr[0])
    end

    trends
  end

  def genre_splitter
    genres = {}

    @movies.each do |movie|
      movie_genres = movie.genre.split(', ')

      movie_genres.each do |genre|
        if genres[genre]
          genres[genre] << movie
        else
          genres[genre] = [movie]
        end
      end
    end

    genres
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :body,
    presence: true

  validates :movie,
    presence: true
end

app/models/trending_movies.rb
class TrendingMovies
  def initialize(movies)
    @movies = movies
  end

  def find_movies(limit=5)
    trends = Hash.new({})

    @movies.each do |movie|
      trends[movie.id] = movie.reviews.count
    end

    trends = trends.sort_by { |reviews| reviews.count}
    trends = trends[0..limit-1]

    trends = trends.map do |arr|
      Movie.find(arr[0])
    end

    trends
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :movies

  mount_uploader :profile_photo, ProfilePhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :sign_in_count, presence: true
  validates :user_name, presence: true

  def update_admin_status
    update_attributes(admin: true)
    save
  end

  def admin?
    admin
  end
end

app/models/user_vote.rb
class UserVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates :user,
    uniqueness: { scope: [:review, :vote_type] },
    presence: true

  validates :review,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).concat [:user_name, :profile_photo]
    devise_parameter_sanitizer.for(:account_update).concat [:user_name, :profile_photo]
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/auto_complete_controller.rb
class AutocompleteController < ApplicationController

  def index
    @movies = Omdb::Api.new.search(params[:q])

    JSON.parse(@movies[:movies].to_json).map{ |m| m['title'] }
  end

end

app/controllers/autocomplete_controller.rb
class AutocompleteController < ApplicationController
  def index
    movies = Omdb::Api.new.search(params[:q])
    json_movies = JSON.parse(movies[:movies].to_json).map { |m| m["title"] }
    respond_to do |format|
      format.js { render json: json_movies }
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:edit, :update, :show]

  def index
    @movies = Movie.order(:title)
    @trending_movies = MovieHelper.new(@movies).find_movies
    @genres = MovieHelper.new(@movies).genre_splitter
  end

  def show
    @movie = Movie.find(params[:id])
    @review = Review.new

    render :show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    omdb_movie = Omdb::Api.new.fetch(movie_params[:title])
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    get_movie

    if @movie.save
      flash[:notice] = 'Movie Successfully Created'
      redirect_to movies_path
    else
      flash[:errors] = @movie.errors.full_messages.join(' ')
      render :new
    end
  end



  def update
    @movie.user = current_user

    if @movie.update(movie_params)
      flash[:notice] = 'Movie Revised'
      redirect_to movie_path(@movie)
    else
      flash[:alert] = @movie.errors.full_messages

      render :edit
    end
  end

  def destroy
    Movie.find(params[:id]).destroy
    redirect_to movies_path
  end

  def get_movie
    omdb_movie = Omdb::Api.new.fetch(movie_params[:title])
    @movie.year = omdb_movie[:movie].year
    @movie.poster = omdb_movie[:movie].poster ? omdb_movie[:movie].poster : ''
    @movie.genre = omdb_movie[:movie].genre
    @movie.director = omdb_movie[:movie].director
    @movie.actors = omdb_movie[:movie].actors
    @movie.runtime = omdb_movie[:movie].runtime
    @movie.rated = omdb_movie[:movie].rated
    @movie.plot = omdb_movie[:movie].plot
    @movie.imdb_id = omdb_movie[:movie].imdb_id
  end


  protected

  def movie_params
    params.require(:movie).permit(:title)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :destroy]

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user

    if @review.save
      ReviewNotifier.new_review(@review).deliver_later
      flash[:notice] = 'Review Successfully Created'
      redirect_to movie_path(@movie)
    else
      @review.errors.full_messages.each { |message| flash[:errors] = message }
      render 'movies/show'
    end
  end

  def update
    @more_votes = true
    @review = Review.find(params[:id])
    @movie = Movie.find(params[:movie_id])
    if params[:votes]
      votes
      if @more_votes
        @review.save
        render 'movies/show'
      end
    elsif @review.update(review_params)
      redirect_to movie_path(@movie)
    else
      @review.errors.full_messages.each { |message| flash[:errors] = message }
      render 'movies/show'
    end
  end

  def destroy
    Review.delete(params[:id])
    flash[:notice] = 'Review deleted'
    @movie = Movie.find(params[:movie_id])
    redirect_to movie_path(@movie)
  end

  def votes
    @review.votes = params[:votes]
    @vote = UserVote.new(review: @review, user: current_user,
                         vote_type: params[:vote_type])
    current_vote = UserVote.find_by(review: @review, user: current_user)
    if current_vote && current_vote.vote_type != @vote.vote_type
      UserVote.delete(current_vote)
    elsif !@vote.save
      respond_to do |format|
        @more_votes = false
        format.js { render 'movies/show', status: 403 }
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:body)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    movies = Movie.where("title iLIKE '%#{params[:q]}%'")

    json_movies = JSON.parse(movies.to_json).map { |m| m["title"] }
    respond_to do |format|
      format.js { render json: json_movies }
    end
  end

  def show_movie
    movie = Movie.find_by(title: params[:search_title])
    if movie
      redirect_to movie_path(movie)
    else
      flash[:alert] = "No movie matches found"
      redirect_to movies_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.limit(100)
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.destroy(params[:id])
    flash[:notice] = 'User Successfully Annihilated'
    redirect_to users_path
  end

  def update
    @user = User.find(params[:id])
    @user.update_admin_status

    if @user.save
      flash[:notice] = 'Admin Successfully Created'
    else
      flash[:errors] = @user.errors.full_messages
    end
    redirect_to users_path
  end
end

app/views/admins/index.html.erb
<ul>
<% @users.each do |user| %>
  <li>
  User Name: <%= user.user_name %><div class="buttons-review delete delete-<%= count %>">
    <span><%= link_to "Delete", movie_review_path(@movie, review), class: "delete-#{count}", method: :delete %></span>
    </div>

    <span>User Email: <%= user.email %></span>
  </li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "MovieHub" %></title>

    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

<body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <%= image_tag "hipsterlogogenerator_1427901012986.png", size: "54x54" %>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to "Add a New Movie", new_movie_path %></li>
        <%- end -%>

        <li class="active"><%= link_to "Home", movies_path %></li>

        <%- if current_user -%>
          <li class="has-dropdown">

            <%= link_to image_tag(current_user.profile_photo, id: "profile-icon"), "#", id: "profile-link", "data-dropdown" => "hover1", "data-options" => "is_hover:true; hover_timeout:5000" %>

            <ul class="dropdown">
              <li><a href="#">View Profile</a></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>

      <ul class="left">
        <li class="has-form">
          <div class="row collapse">
            <%= form_tag(show_movie_path, method: "get") do %>
              <div class="large-8 small-9 columns">
                <%= text_field_tag :search_title, nil, placeholder: "Find a Movie" %>
              </div>
              <div id="titles-list-container">
                <ul id="titles-list"></ul>
              </div>
              <div class="large-4 small-3 columns">
                <%= submit_tag("Search", class: "button", id: "search-button") %>
              </div>
            <% end %>
          </div>
        </li>
      </ul>
    </section>
  </nav>

  <div class="row">
    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>
  </div>

  <div class="row">
    <div class="movie-header">
      <h1>MovieHub</h1>
    </div>
  </div>

  <div class="body-content">

    <%= yield %>

  </div>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/movies/edit.html.erb
<h3>Edit Movie</h3>

<%= form_for @movie do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </p>
  <p>
    <%= f.submit "Update Movie", class: "medium button radius"%>
  </p>
<% end %>

<div data-alert class="alert-box">
  <%= button_to "Delete this Movie", {:controller => :movies,
      :action => 'destroy', :id => @movie.id }, :method =>
      :delete, confirm: "Are you sure?", class: "medium button radius" %>
</div>

app/views/movies/index.html.erb
<div class="large-12 columns main-content">
  <div id="index-page-container">
    <h4 class="genre-title">Feature Presentation</h4>
    <div class="big-carousel-container feature-presentation">
      <% @trending_movies.each do |movie| %>
        <div><%= link_to image_tag(movie.poster, class: "tending-movies-img"), movie_path(movie) %></div>
      <% end %>
    </div>

    <% @genres.keys.each do |genre| %>
      <h6 class="genre-title"><%= genre %></h6>
      <div class="genres-carousel-container slider-nav">
        <% @genres[genre].each do |movie| %>
          <div class="carousel-movie-container">
            <div class="poster-container">
              <%= link_to image_tag(movie.poster, class: "carousel-picture"), movie_path(movie) %>
            </div>
            <div class="title-container">
              <p><%= movie.title %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <ul>
      <% if current_user %>
        <% if current_user.admin? %>
          <h4>You are an Admin: <%= link_to "Got to Admin Functions", users_path %></h4>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/movies/new.html.erb
<h3>Add a Movie</h3>

<div class="row-form">
  <%= form_for @movie do |f| %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: "Insert Movie Title" %>
    </p>
    <div id="titles-list-container">
      <ul id="titles-list"></ul>
    </div>
    <p>
      <%= f.submit "Create a New Movie", class: "medium button radius", id: "movie-submit" %>
    </p>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="row movie-details-container">
  <div class="left-column small-4 columns">
    <div><%= image_tag(@movie.poster) %></div>

    <div class="small-11 columns">
      <h3><%= @movie.title %></h3>
      <p><%= @movie.year %></p>
      <p><%= @movie.genre %> | Rated(<%= @movie.rated %>)</p>
      <p><%= @movie.plot %></p>
    </div>
    <% if current_user && (@movie.user == current_user || current_user.admin?) %>
      <div class="movie-icons">
        <%= link_to image_tag("edit-icon.png"), edit_movie_path(@movie) %>
      </div>
      <div class="movie-icons delete-movie">
        <%= link_to image_tag("delete-icon.png"), movie_path(@movie), method: :delete %>
      </div>
    <% end %>
  </div>

  <div class="right-column small-8 columns">
    <div class="review-container">
      <div class="row right-column top-row">
        <fieldset>
          <legend>Add your review</legend>
          <%= form_for [@movie, @review] do |f|%>
            <div class="field">
              <%= f.text_area :body %>
            </div>
            <div>
              <%= f.submit "Submit Review", class: "tiny button radius"%>
            </div>
          <% end %>
        </fieldset>
      </div>

      <div class="row right-column bottom-row">

        <div class="small-1 column">
        </div>

        <% if !@movie.reviews.empty? %>
          <% count = 0 %>
          <% @movie.reviews.order('created_at').each do |review| %>
            <fieldset class="row review-<%= count %>">
            <legend><%= review.user.user_name %></legend>
              <div class="small-1 column">
                <div class="vote-up">
                  <%= link_to image_tag("up-vote.png"), "#", num: count, movie_id: @movie.id, review_id: review.id %>
                </div>
                <p class="icons votes votes-<%= count %>"><%= review.votes %></p>
                <div class="vote-down">
                  <%= link_to image_tag("down-vote.png"), "#", num: count, movie_id: @movie.id, review_id: review.id %>
                </div>
              </div>
              <p class="small-10 columns review-body-<%= count %>"><%= review.body %></p>
              <% if current_user && (review.user == current_user || current_user.admin?) %>
                <div class="small-10 columns review-form review-form-<%= count %>">
                  <%= form_for [@movie, review] do |f|%>
                    <div class="field">
                      <%= f.text_area :body %>
                    </div>
                    <div class="actions">
                      <%= f.submit %>
                    </div>
                  <% end %>
                </div>
                <div class="small-1 column">
                  <div class="icons edit-review edit-<%= count %>">
                    <%= link_to image_tag("edit-icon.png"), "#", name: count %>
                  </div>

                  <div class="icons delete-review delete-<%= count %>">
                    <%= link_to image_tag("delete-icon.png"), movie_review_path(@movie, review), method: :delete %>
                  </div>

                  <div class="icons cancel-review cancel-<%= count %>">
                    <%= link_to image_tag("delete-icon.png"), '#', name: count %>
                  </div>
                </div>
              <% end %>
            <% count += 1 %>
            </fieldset>
          <% end %>
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/review_notifier/new_review.text.erb
Hello <%= @review.movie.user.user_name %>,

<%= @review.user.user_name %> has left a new review for your product <%= @review.movie.title %>.

Peace!

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li>
      User Name: <%= user.user_name %>

      <div>
        <% if current_user.admin? %>
          <%= button_to 'Delete User', user, method: :delete, class: "medium button radius" %>
          <%= button_to "Make #{user.user_name} Admin",
            { action: "update", id: user.id }, { method: :patch, class: "medium button radius" } %>
        <% end %>
      </div>

      <span>User Email: <%= user.email %></span>

    </li>
  <% end %>
</ul>